### PR TITLE
UI Updates

### PR DESCRIPTION
**Pull request by mtpultz**
* Updated user used for immunization records, 
* Updated user to have a 3rd vaccination, 
* Updated wording on login

Signed-off-by: Martin Pultz <mtpultz@gmail.com>

### CODE REVIEW

**Comment by swcurran** [comment]
Any trick to seeing the changes?  I did the normal checkout, build, start and did not get the changes in the UI.

Hmm...caching in the browser?

Right now, trying `build --no-cache`, `rm`, `start`

**Comment by swcurran** [comment]
Yup...it was caching.  :-)  Doh...

**Comment by mtpultz** [comment]
@swcurran not much time to get this in and have it built for the demo.  Can you please approve it, and afterwards I can try and unblock you

**Review by swcurran — APPROVED** [review]
LGTM

**Review by AnaisHebert — APPROVED** [review]

**Comment by swcurran** [comment]
Great work.

**Pull request merged**
