### PR TITLE
Allow overriding of service ports as needed

### LINKED ISSUE #65: Mac OS - ports
For info, on my mac:
CISCO Anyconnect VPN uses port 5001
Apple Airport Utility uses port 8021

I uninstalled CISCO and restarted
I disabled Airport Utility

### PR DESCRIPTION
**Pull request by esune**
Resolves #65

### CODE REVIEW

**Comment by swcurran** [comment]
Need to add to the readme or perhaps better, the manage script the names (and defaults) of all of the ports.

I'm torn on the length of all the port names -- they are pretty long for interactive use.  Putting it in the manage script at least makes it easy to copy/paste the values.

**Comment by esune** [comment]
> 
> 
> Need to add to the readme or perhaps better, the manage script the names (and defaults) of all of the ports.
> 
> I'm torn on the length of all the port names -- they are pretty long for interactive use. Putting it in the manage script at least makes it easy to copy/paste the values.

Readme added, with detailed list of ports and explanation on how to override them. The french version of the readme needs updating accordingly, I could give it a stab using Google translate and some guesswork based on Spanish/Italian grammar, but I think one of the folks from Quebec would do a much better job in a fraction of the time 😉 

I am honestly not too concerned about the port names: based on the experience so far (with the other projects we created/support), it seems like the need to change the defaults is almost a one-off and  most people are likely NOT going to need to change anything.

**Comment by swcurran** [comment]
@esune -- could you update to fix the conflict?  It's a trivial change fortunately.  Thanks!

**Comment by esune** [comment]
@swcurran it should be good to go now.

**Review by swcurran — APPROVED** [review]

**Pull request merged**
