### PR TITLE
Translation of UI.

### PR DESCRIPTION
**Pull request by foxbike**
Here are the changes to display the user interface in English and French.

### CODE REVIEW

**Comment by swcurran** [comment]
Testing this out, but @foxbike -- you need to sign your commits for DCO (Developer Certificate of Origin).  See the "Details" link above, beside the "DCO" check.  If you use git command line, you have to do `git commit -s -m "my commit message"` -- the -s is necessary.

**Comment by swcurran** [comment]
Looks good and ran nicely.  Looks like there are still some things needed:

- add a way to get to the landing point in the desired language -- perhaps: `http://localhost:4200/en` and `http://localhost:4200/fr`
- a way for a specific deployment to pick the default language when just hitting the home page `http://localhost:4200`
- a language selector on the front page
- getting the language selector to work from the footer -- at least it didn't work for me.

Great work!

**Comment by mtpultz** [comment]
@swcurran definitely those are updates that we're aware need implementation, but we'd prefer to have them addressed in separate tickets to keep PR complexity and volume of changes on merge down since we'll already going to have merge conflicts with my incoming changes.

**Review by mtpultz — DISMISSED** [review]
image

**Review by mtpultz — APPROVED** [review]
image

**Pull request merged**
